### ISSUE TITLE
Failing assert in debug builds during weval IC cache generation

### ISSUE THREAD

**Issue by tschneidereit** [bytecodealliance/StarlingMonkey#149]
STR (from within a checkout of current `main`):
```sh
cmake -S . -B cmake-build-weval -DCMAKE_BUILD_TYPE=Debug -DUSE_WASM_OPT=OFF -DWEVAL=ON
cmake --build cmake-build-weval --parallel 12 --target all integration-test-server
```

Expected result:
The build succeeds.

Actual result:
The build fails with this message:
```
[-1] Assertion failure: stubInfo->stubDataSize() == writer.stubDataSize(), at /home/runner/work/spidermonkey-wasi-embedding/spidermonkey-wasi-embedding/gecko-dev/js/src/jit/BaselineCacheIRCompiler.cpp:2653
```

Our CI only tests release builds of weval, so this hasn't been caught yet.

CC @cfallin

**Comment by cfallin** [comment]
I'll take a look, thanks! I have quite a backlog of work at the moment but hopefully will get to this soon.

**Comment by cfallin** [comment]
Adding some notes from today's investigations so far:

- This is happening during rehydration of the AOT IC corpus and loading it into the IC compiler data structures.
- The `stubDataSize` on the `CacheIRWriter` is larger than that on the `CacheIRStubInfo`.
- It appears this is because there are word-sized fields; `CacheIRWriter` computes a size and we dump that size, so the corpus when built on a 64-bit machine has 64-bit-dependent sizes; `CacheIRStubInfo` recomputes the size based on the host machine's memory model, which on wasm32 hsa 32-bit words.
- This mismatch is *OK* because the size computed by `CacheIRWriter` is *only* used by this assert and nowhere else; it's a redundant check, it's not load-bearing. Striclty speaking we shouldn't need to persist it.
- However, skipping the assert conditionally when rehydrating the corpus leads to other, more exciting errors indicating that specialization of IC bodies is running off the end of some bytecode ("non-constant" parameters because loads aren't constant past the bytecode blob). I'm fairly perplexed why this is happening only in debug builds; have been looking for anything else that could cause a difference in formats or ser/deser mismatch issues when in a debug build.

Currently stuck at the last point above and still digging.

**Comment by cfallin** [comment]
(In case it's any concern: I'm not worried about execution correctness bugs hinted at by this because in the worst case, AOT IC loading puts bogus random IC bodies in the hashtable and no IC lookup uses them; in other words, we may build in and compile the wrong ICs, but we'll never execute them unknowingly.)

**Comment by cfallin** [comment]
Alright, a little more investigation: it turns out that there is a fairly fundamental problem with weval'ing PBL's IC interpreter when built in debug mode: its "pc" (advancing pointer through bytecode), which needs to be a Wasm local for weval to track and const-propagate it, is instead a variable on the stack frame, loaded and stored constantly, in a debug build. This is because it's a member variable of a `CompactBuffer` instance. The resulting `Runtime` (not constant-known) pointer propagates through to `Runtime` bytecode parameters which is what's leading to the above issues.

From one point of view, it's a little brittle to depend on a variable being a Wasm local, but then from another, it's even moreso to depend on complex alias analysis to try to see through what the compiler has done with memory and undo it. I developed weval on release-compiled code from the beginning partly for this reason.

(One way to see this: as opposed to SpiderMonkey's JITs, which will produce (approximately) the same machine code whether or not the compiler itself is built with `DEBUG`, wevaled-SpiderMonkey is taking pieces of the engine's code and stitching them together, so it matters how much the engine is actually optimized. The execution speed is hence not going to be as expected either.)

I could refactor the IC interpreter loop to use a true local (`uint8_t* pc;`) as the JS opcode loop does, with macros to read, but that would have to inline all of the existing `CacheIRReader` machinery, which is unlikely to be seen by upstream as a desirable refactor, so I'm not too excited to go in that direction. 

I'm curious what @tschneidereit and @guybedford think of the above: is there appetite to simply say "weval works on optimized code", or is there a strong need to support a debug build for a use-case not served by non-weval'd debug builds?

**Comment by guybedford** [comment]
Making Weval release-build-only seems fine to me, but I'll let @tschneidereit chime in further.

If we decide to go this route it would be nice to make it an explicit assertion and build error otherwise to build for Weval in a non release mode.

**Comment by cfallin** [comment]
Indeed, I can add an `#ifdef DEBUG`/`#error` at the top of PBL's main file to make it explicit if we decide that.
